[package]
name = "cola2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
num-bigint = "0.4.3"
num-traits = "0.2.14"
